Change storage location from CSV to DB
Chi-rr/Fjord_Sinatra_Memo pull request #1
Opened 2020-06-20 09:08 UTC by Chi-rr

2020-06-22 02:45 UTC, komagata requested changes

2020-06-22 02:45 UTC, komagata commented on db.rb
> +    @conn.exec("DELETE FROM memo WHERE id= #{params[:id]}")
SQLにデータを埋め込むにはプレースフォルダの機能を使わないとSQL Injectionが発生しちゃいます。

ちょっと調べてみてください〜。

2020-06-24 02:59 UTC, komagata requested changes

2020-06-24 02:59 UTC, komagata commented on db.rb
> +  def delete_row(params)
idのみが必要なのであれば引数は`id`でいいと思います。

2020-06-24 14:06 UTC, komagata requested changes

2020-06-24 14:06 UTC, komagata commented on db.rb
> +  def update_row(params)
このメソッドもparamsがどういう構造なのかわからないのでなるべく明示的に引数を渡した方がいいと思います。（なんでも渡せるように汎用的にする必要がある場合は違いますが。）

2020-06-25 04:23 UTC, komagata requested changes

2020-06-25 04:23 UTC, komagata commented on db.rb
> +    result.each { |tuple| @rows << [tuple["id"], tuple["memo_name"]] }
execが返しているのがhashの配列だとしたら別の変数に詰め直さなくてもそのままで使えるんじゃないでしょうか。

またtupleは配列に近いデータ構造なので名前でアクセスできるデータ構造にtupleとつけると紛らわしいかもです。

2020-06-25 09:16 UTC, Chi-rr commented on db.rb
> +    result.each { |tuple| @rows << [tuple["id"], tuple["memo_name"]] }
@komagata
ご確認いただきありがとうございます！！
>execが返しているのがhashの配列だとしたら別の変数に詰め直さなくてもそのままで使えるんじゃないでしょうか。

db.rbのrow, rows, select_idのメソッドを修正し、それに伴うapp.rb/views(index, show, edit)も修正してみました。

>tupleは配列に近いデータ構造なので名前でアクセスできるデータ構造にtupleとつけると紛らわしい

ご指摘ありがとうございます🙌 適宜名前も変更してみました。

よろしくお願いします！

2020-06-26 02:31 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-06-27 00:19 UTC, merged